"""add price_targets table

Revision ID: 141a8cdb8fbc
Revises: 669ea7b4f799
Create Date: 2026-03-23 15:17:51.125822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141a8cdb8fbc'
down_revision: Union[str, Sequence[str], None] = '669ea7b4f799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_targets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('direction', sa.String(length=10), server_default='below', nullable=False),
    sa.Column('alert_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('above', 'below')", name='valid_direction'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_targets_active', 'price_targets', ['alert_enabled', 'triggered_at'], unique=False, postgresql_where=sa.text('alert_enabled = true AND triggered_at IS NULL'))
    op.create_index('idx_targets_watchlist', 'price_targets', ['watchlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_targets_watchlist', table_name='price_targets')
    op.drop_index('idx_targets_active', table_name='price_targets', postgresql_where=sa.text('alert_enabled = true AND triggered_at IS NULL'))
    op.drop_table('price_targets')
    # ### end Alembic commands ###
