"""add journal_entries table

Revision ID: 318c75f15cf0
Revises: 141a8cdb8fbc
Create Date: 2026-03-23 15:22:34.196746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '318c75f15cf0'
down_revision: Union[str, Sequence[str], None] = '141a8cdb8fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), server_default='note', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entry_type IN ('thesis', 'note', 'entry', 'exit', 'adjustment', 'review')", name='valid_entry_type'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_journal_type', 'journal_entries', ['entry_type'], unique=False)
    op.create_index('idx_journal_watchlist', 'journal_entries', ['watchlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_journal_watchlist', table_name='journal_entries')
    op.drop_index('idx_journal_type', table_name='journal_entries')
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
