"""create watchlist_items table

Revision ID: 669ea7b4f799
Revises: 
Create Date: 2026-03-23 14:52:50.387328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '669ea7b4f799'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='watching', nullable=False),
    sa.Column('position_type', sa.String(length=10), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('shares_or_contracts', sa.Integer(), nullable=True),
    sa.Column('cost_basis', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('watching', 'position_open', 'closed')", name='valid_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_watchlist_status', 'watchlist_items', ['status'], unique=False)
    op.create_index('idx_watchlist_ticker', 'watchlist_items', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_watchlist_ticker', table_name='watchlist_items')
    op.drop_index('idx_watchlist_status', table_name='watchlist_items')
    op.drop_table('watchlist_items')
    # ### end Alembic commands ###
