"""add alerts and alert_history tables

Revision ID: d4e3d91957d2
Revises: 318c75f15cf0
Create Date: 2026-03-25 09:50:29.593507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4e3d91957d2'
down_revision: Union[str, Sequence[str], None] = '318c75f15cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('watchlist_id', sa.UUID(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('priority', sa.String(length=10), server_default='normal', nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("alert_type IN ('price_cross', 'earnings_check', 'date_reminder', 'technical_signal', 'custom')", name='valid_alert_type'),
    sa.CheckConstraint("priority IN ('low', 'normal', 'high', 'urgent')", name='valid_alert_priority'),
    sa.CheckConstraint("status IN ('active', 'triggered', 'dismissed', 'expired')", name='valid_alert_status'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_active', 'alerts', ['status'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('idx_alerts_ticker', 'alerts', ['ticker'], unique=False)
    op.create_index('idx_alerts_type', 'alerts', ['alert_type'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('condition_met', sa.Boolean(), nullable=False),
    sa.Column('actual_value', sa.Numeric(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_history_alert', 'alert_history', ['alert_id'], unique=False)
    op.create_index('idx_alert_history_triggered', 'alert_history', ['condition_met'], unique=False, postgresql_where=sa.text('condition_met = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alert_history_triggered', table_name='alert_history', postgresql_where=sa.text('condition_met = true'))
    op.drop_index('idx_alert_history_alert', table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index('idx_alerts_type', table_name='alerts')
    op.drop_index('idx_alerts_ticker', table_name='alerts')
    op.drop_index('idx_alerts_active', table_name='alerts', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('alerts')
    # ### end Alembic commands ###
